global:
  application_name: django-app
  default_platform: null
  default_region: us-east-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  workspace_type: Application
